### ISSUE TITLE
conda installation instructions do not work

### ISSUE THREAD

**Issue by gerritholl** [ssec/sift#251]
According to the `README.MD`:

> Installing with Conda
> --

> SIFT can also be installed with the Anaconda/Conda package manager. Python 3.7 is currently the only supported python environment. It can be installed by running:

> `conda install -c http://larch.ssec.wisc.edu/channels/sift uwsift`

This is incorrect.  Following these instructions will result in a `PackagesNotFoundError` for `uwsift`.  There [is a package `sift-1.0.6`](http://larch.ssec.wisc.edu/channels/sift/linux-64/) there, but for Python 3.6, directly contradicting the line in the `README.md` stating that sift is available only for Python 3.7.  An attempt of `conda install -c http://larch.ssec.wisc.edu/channels/sift sift` results in a `UnsatisfiableError`:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

  - sift -> python[version='2.7.*,>=2.7,<2.8.0a0']

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to.  Your current python version
is (python=3.7).  Note that conda will not change your python version to a different minor version
unless you explicitly specify that.

The following specifications were found to be incompatible with each other:



Package wheel conflicts for:
sift -> satpy[version='>=0.10.0a0'] -> trollimage[version='>=1.5.1'] -> rasterio -> attrs[version='>=16.0.0'] -> hypothesis -> enum34 -> python[version='2.7.*,>=2.7,<2.8.0a0'] -> pip -> wheel
python=3.7 -> pip -> wheel
Package certifi conflicts for:
sift -> satpy[version='>=0.10.0a0'] -> trollimage[version='>=1.5.1'] -> rasterio -> attrs[version='>=16.0.0'] -> hypothesis -> enum34 -> python[version='2.7.*,>=2.7,<2.8.0a0'] -> pip -> wheel -> setuptools -> certifi[version='>=2016.09']
python=3.7 -> pip -> wheel -> setuptools -> certifi[version='>=2016.09']
Package pip conflicts for:
python=3.7 -> pip
sift -> satpy[version='>=0.10.0a0'] -> trollimage[version='>=1.5.1'] -> rasterio -> attrs[version='>=16.0.0'] -> hypothesis -> enum34 -> python[version='2.7.*,>=2.7,<2.8.0a0'] -> pip
Package setuptools conflicts for:
python=3.7 -> pip -> wheel -> setuptools
sift -> satpy[version='>=0.10.0a0'] -> trollimage[version='>=1.5.1'] -> rasterio -> attrs[version='>=16.0.0'] -> hypothesis -> enum34 -> python[version='2.7.*,>=2.7,<2.8.0a0'] -> pip -> wheel -> setuptools
Note that strict channel priority may have removed packages required for satisfiability.
```

The [repodata](http://larch.ssec.wisc.edu/channels/sift/linux-64/repodata.json) there contain a requirement `"python >=3.6,<3.7.0a0"`, so it's not installable under Python 3.7.

I did not try an installation under Python 3.6 or Python 3.8.

**Comment by djhoese** [comment]
There is currently a disconnect between the instructions on github and what is actually available. The instructions have been updated for the new release I hope to get out by the end of November. Since it hasn't been released yet the packages don't actually exist.

**Comment by gerritholl** [comment]
I see.  There's a problem using `pip install` from the github tag `1.0.6` as well — there is a dependency (listed twice) on a package called `goesr`, which is slightly hidden at `https://gitlab.ssec.wisc.edu/rayg/goesr`

**Comment by djhoese** [comment]
Sorry this is so difficult. You *should* be able to do:

```
pip install git+https://gitlab.ssec.wisc.edu/rayg/goesr.git
```

Then do the pip install from the github tag.

In future versions we aren't even going to use the goesr package which is why it isn't available on something like PyPI.

**Comment by gerritholl** [comment]
There is also an inconsistency for the documented version needs of `PyQt4` or `PyQt5`.  The docstring in `setup.py` says it needs `PyQt4`, but the `install_requires` says it needs `PyQt5`.  The former appears unavailable for Python 3.7, which I suppose is why v1.0.6 works only for Python 3.6 but the latest master works only for Python 3.7?

**Comment by djhoese** [comment]
PyQt4/5 is one of the reasons there is such a huge inconsistency with the instructions. We are switching to PyQt5 because conda-forge no longer supports PyQt4 (not that I blame them, it's old). I started having to build custom versions of matplotlib and copying old PyQt4 builds to keep SIFT packaging possible.

Old versions (1.0.6 and earlier) use PyQt4, new versions use PyQt5.

**Comment by gerritholl** [comment]
Right... and then `pypi` has a package called `PyQt5`, whereas `conda-forge` has a package `pyqt` for which there is a version 5.9.2, if I `pip install` the latest git master it still wants to install `PyQt5` from pypi even though I already have `pyqt` from `conda-forge`...  When I try a regular `pip install` from the latest git master (which results in the installation of `pyqt5` 5.13 next to `pyqt` 5.9) trying to run `python -m uwsift` results in a `ModuleNotFoundError`, I guess due to confusion between versions...   will try more after the weekend.

**Comment by gerritholl** [comment]
The `ModuleNotFoundError` was/is for `quamesh` which is apparently also a separate package missing from the requirements in `setup.py` (and not available on conda-forge).  I got a step further by separately running `pip install quamesh`.

**Comment by gerritholl** [comment]
After installing `quamesh` manually, I'm getting an `AssertionError` because the colourmap files are not installed as expected:

```
Traceback (most recent call last):
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/uwsift/__main__.py", line 40, in <module>
    from uwsift.control.doc_ws_as_timeline_scene import SiftDocumentAsFramesInTracks
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/uwsift/control/doc_ws_as_timeline_scene.py", line 18, in <module>
    from uwsift.model.document import Document, DocumentAsTrackStack, FrameInfo, TrackInfo
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/uwsift/model/__init__.py", line 25, in <module>
    from uwsift.model.document import Document  # noqa
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/uwsift/model/document.py", line 78, in <module>
    from uwsift.workspace.metadatabase import Product
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/uwsift/workspace/__init__.py", line 25, in <module>
    from .workspace import Workspace  # noqa
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/uwsift/workspace/workspace.py", line 61, in <module>
    from .importer import aImporter, SatpyImporter, generate_guidebook_metadata
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/uwsift/workspace/importer.py", line 28, in <module>
    from uwsift.workspace.guidebook import ABI_AHI_Guidebook, Guidebook
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/uwsift/workspace/guidebook.py", line 22, in <module>
    from uwsift.view.colormap import DEFAULT_IR, DEFAULT_VIS, DEFAULT_UNKNOWN
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/uwsift/view/colormap.py", line 606, in <module>
    ('CA (Low Light Vis)', LazyColormap(AWIPSColormap, os.path.join(AWIPS_DIR, 'VIS', 'CA (Low Light Vis).cmap'))),
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/uwsift/view/colormap.py", line 598, in __init__
    assert os.path.isfile(self.cmap_file)
AssertionError
```

Here `self.cmap_file` has the value `/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/uwsift/data/colormaps/OAX/GOES-R/VIS/CA (Low Light Vis).cmap`.  Although there is a `data/` directory in the github repository, `pip install` does not appear to install this into the installation directory.

**Comment by gerritholl** [comment]
To reproduce this in a fresh environment:

```
conda create -n py37_sandbox python=3.7
conda activate py37_sandbox
conda install vispy pyopengl pyqt netCDF4 pyproj h5py shapely rasterio pyyaml satpy numba pyqtgraph pygrib pyshp sqlalchemy imageio
pip install quamash git+https://gitlab.ssec.wisc.edu/rayg/goesr.git git+https://github.com/ssec/sift.git
python -m uwsift
```

**Comment by djhoese** [comment]
This is a known issue and is fixed in #246. We are also dropping quamash as a dependency in #248 since it isn't actually used and is unmaintained. We should hopefully have these merged by the end of the day (CC @katherinekolman).

**Comment by gerritholl** [comment]
Another unlisted dependency is `matplotlib`, not sure if that's being resolved in a pending pull request.

I can confirm that I'm finally able to start `sift` when installing from https://github.com/katherinekolman/sift/commit/2f36231ae3688ad8b3c934bfbd6f657b17fa2ab4 , although still having problems in some cases, presumably due to a conflict between `pyqt 5.9.2` installed from conda-forge and `pyqt5 5.13.1` installed from pypi.

**Comment by djhoese** [comment]
If you don't have the newest pyqt from conda-forge then yes there may be problems. @katherinekolman worked on some of this in the last month. Conda-forge dropped some WebEngine functionality from their builds of pyqt that we were using. I *think* it should work fine with Qt 5.9+ though so I'm surprised you're having an issue. If you have both a PyPI and a conda version installed though then that could definitely be the problem.

The matplotlib dependency missing is...surprising. @katherinekolman Could you add this to `setup.py` in your tests PR?

**Comment by gerritholl** [comment]
NB: when I moved from https://github.com/katherinekolman/sift/commit/2f36231ae3688ad8b3c934bfbd6f657b17fa2ab4 to https://github.com/ssec/sift/commit/dd831cc3273c6c166d1c7699505935e66dbddcda I found that I had to delete my cache; without deleting the cache I was getting a traceback.  Not sure if this should be considered a bug as I wasn't coming from a regular installation, but if there are cache incompatibilities between "official" versions then probably the installation process should clear the cache.

When deleting the cache the problem went away.

```
WARNING 10:56:04 metadatabase:__exit__:L776 an exception occurred, rolling back any metadatabase changes
ValueError: 'band' is not a valid Info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/uwsift/__main__.py", line 1207, in <module>
    sys.exit(main())
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/uwsift/__main__.py", line 1195, in main
    clear_workspace=args.clear_workspace,
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/uwsift/__main__.py", line 739, in __init__
    self._init_menu()
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/uwsift/__main__.py", line 1087, in _init_menu
    self.update_recent_file_menu()
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/uwsift/__main__.py", line 511, in update_recent_file_menu
    uuid_to_name = self.workspace.recently_used_products()
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/uwsift/workspace/workspace.py", line 722, in recently_used_products
    for p in s.query(Product).order_by(Product.atime.desc()).limit(n).all())
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/uwsift/workspace/workspace.py", line 722, in <genexpr>
    for p in s.query(Product).order_by(Product.atime.desc()).limit(n).all())
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/uwsift/workspace/metadatabase.py", line 363, in info
    self._info = ChainRecordWithDict(self, self.INFO_TO_FIELD, self._kwinfo)
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/sqlalchemy/ext/associationproxy.py", line 193, in __get__
    return inst.get(obj)
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/sqlalchemy/ext/associationproxy.py", line 548, in get
    _lazy_collection(obj, self.target_collection)
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/sqlalchemy/ext/associationproxy.py", line 589, in _new
    collection_class = util.duck_type_collection(lazy_collection())
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/sqlalchemy/ext/associationproxy.py", line 920, in __call__
    return getattr(self.parent, self.target)
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 282, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 710, in get
    value = self.callable_(state, passive)
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 730, in _load_for_state
    session, state, primary_key_identity, passive
  File "<string>", line 1, in <lambda>
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 872, in _emit_lazyload
    .with_post_criteria(set_default_params)
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/sqlalchemy/ext/baked.py", line 531, in all
    return list(self)
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 105, in instances
    util.raise_from_cause(err)
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 85, in instances
    rows = [proc(row) for row in fetch]
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 85, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 508, in _instance
    tuple([row[column] for column in pk_cols]),
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 508, in <listcomp>
    tuple([row[column] for column in pk_cols]),
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1684, in process
    return loads(value)
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/enum.py", line 310, in __call__
    return cls.__new__(cls, value)
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/enum.py", line 564, in __new__
    raise exc
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/enum.py", line 548, in __new__
    result = cls._missing_(value)
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/enum.py", line 577, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'band' is not a valid Info
```

**Comment by djhoese** [comment]
This is expected given some of the recent changes I made (#247) and is generally needed between versions. We don't currently have a way to automatically detect that a workspace needs to be cleared/reset when there are breaking changes and I'm not sure it is something SIFT should do automatically. There could definitely be a better error message/detection.

The easiest way to delete the workspace/cache is to specify `--clear-workspace` on the command line the first time you start up SIFT.

**Comment by djhoese** [comment]
This should now be fixed as of the `1.1.0` release of SIFT. There are a few bugs with some SEVIRI data, but otherwise the installation seems to work fine.

https://github.com/ssec/sift/wiki/installation-guide#python-package-installation
